# Numpy 26/09/2022

In [50]:
#NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
import numpy as np

# Create simple array from the list

In [51]:
ar = np.array([[1,2,3],[4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
type(ar)

numpy.ndarray

In [53]:
a = np.array([['a','b','c'],['d','e','f']])
a

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [54]:
type(a)

numpy.ndarray

In [55]:
#dimention of array
arr.ndim

2

In [56]:
a.ndim

2

In [57]:
#shape of array
arr.shape

(3, 5)

In [58]:
a.shape

(2, 3)

In [59]:
#3d in 5 ele in each row
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array is : ",arr)
print("Dimension of array is : ",arr.ndim)
print("Matrix : " ,arr.shape)

Array is :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension of array is :  2
Matrix :  (3, 5)


In [60]:
print(arr.data)
print(a.data)
print(ar.data)

# Random Number Generator using NumPy

In [64]:
from numpy import random

In [72]:
x= random.randint(100) #range in between 0 to 100
x

82

In [82]:
#task 5 random number 0 to 1000
for x in range(0,5):
    y=random.randint(1000)
    print(y)

799
812
769
618
869


In [84]:
for x in range(0,10,2):
    y=random.randint(1000)
    print(y)

623
342
569
217
787


In [85]:
#Generate the random float number
f = random.rand()
f

0.5338088605591444

In [87]:
for x in range(0,11):
    f = random.rand()
    print(f)

0.3214008106331119
0.643252830334287
0.654057063342149
0.699153497739328
0.41390884191574173
0.861065659366103
0.7695273136535847
0.7441984112515807
0.48242181304456355
0.6403517289516565
0.3751651933364716


In [88]:
x =random.randint(100,size=(10))
x

array([46, 33, 25, 24, 65, 31, 20, 35, 36, 52])

In [90]:
x =random.randint(100,size=(10,10))
x

array([[90, 47,  7, 44, 77, 71, 27, 91, 85, 13],
       [35, 80, 11, 36, 53, 82, 21, 19, 10,  6],
       [15, 12, 13, 23, 51, 88, 46, 44,  7, 57],
       [12, 74, 24, 86, 77, 81, 28, 92, 75, 45],
       [77, 67, 61, 50,  5, 82, 34, 28, 66, 57],
       [33, 52, 65, 62, 84, 48, 43, 24, 12, 10],
       [53, 19, 42, 52,  3, 68, 63, 50, 49, 97],
       [13, 81, 86, 54,  0, 88,  5, 50, 31, 35],
       [56, 35, 91, 16, 33, 99, 57,  5, 67, 47],
       [14, 19, 76, 36,  9, 26, 54, 69, 30, 55]])

In [91]:
x.shape

(10, 10)

In [92]:
x.ndim

2

# 2.8 Measures of Central Tendency

In [111]:
#Generate random array (3,3)
x = random.randint(10, size=(3,3))
x

array([[0, 6, 1],
       [6, 9, 1],
       [1, 0, 6]])

In [112]:
#Min Value
print(np.amin(x))

0


In [113]:
#Max Value
print(np.amax(x))

9


# Mean Median Standard Deviation and Variance

In [114]:
print("Mean of array : ",np.mean(x))
print("Median of array : ",np.median(x))
print("StandardDeviation of array : ",np.std(x))
print("Variance of array : ",np.var(x))

Mean of array :  3.3333333333333335
Median of array :  1.0
StandardDeviation of array :  3.197221015541813
Variance of array :  10.222222222222221


# Array Broadcasting using NumPy

In [123]:
x = random.randint(100,size=(5))
y = random.randint(10,size=(5))
print(x)
print(y)

[84 94 45 64 43]
[2 9 7 2 8]


In [124]:
x+y

array([ 86, 103,  52,  66,  51])

In [125]:
x*y

array([168, 846, 315, 128, 344])

In [126]:
x/y

array([42.        , 10.44444444,  6.42857143, 32.        ,  5.375     ])